.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH GENPKEY 1 "1.0.1e" "11/Feb/2013" "OpenSSL"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
genpkey \- generate a private key
.SH "SYNOPSIS"
\fBopenssl\fR \fBgenpkey\fR
[\fB\-out filename\fR]
[\fB\-outform PEM|DER\fR]
[\fB\-pass arg\fR]
[\fB\-cipher\fR]
[\fB\-engine id\fR]
[\fB\-paramfile file\fR]
[\fB\-algorithm alg\fR]
[\fB\-pkeyopt opt:value\fR]
[\fB\-genparam\fR]
[\fB\-text\fR]
.SH "DESCRIPTION"
The \fBgenpkey\fR command generates a private key.
.SH "OPTIONS"
.Ip "\fB\-out filename\fR" 4
the output filename. If this argument is not specified then standard output is
used.  
.Ip "\fB\-outform \s-1DER\s0|\s-1PEM\s0\fR" 4
This specifies the output format \s-1DER\s0 or \s-1PEM\s0.
.Ip "\fB\-pass arg\fR" 4
the output file password source. For more information about the format of \fBarg\fR
see the \fB\s-1PASS\s0 \s-1PHRASE\s0 \s-1ARGUMENTS\s0\fR section in openssl(1).
.Ip "\fB\-cipher\fR" 4
This option encrypts the private key with the supplied cipher. Any algorithm
name accepted by \fIEVP_get_cipherbyname()\fR is acceptable such as \fBdes3\fR.
.Ip "\fB\-engine id\fR" 4
specifying an engine (by its unique \fBid\fR string) will cause \fBgenpkey\fR
to attempt to obtain a functional reference to the specified engine,
thus initialising it if needed. The engine will then be set as the default
for all available algorithms. If used this option should precede all other
options.
.Ip "\fB\-algorithm alg\fR" 4
public key algorithm to use such as \s-1RSA\s0, \s-1DSA\s0 or \s-1DH\s0. If used this option must
precede any \fB\-pkeyopt\fR options. The options \fB\-paramfile\fR and \fB\-algorithm\fR
are mutually exclusive.
.Ip "\fB\-pkeyopt opt:value\fR" 4
set the public key algorithm option \fBopt\fR to \fBvalue\fR. The precise set of
options supported depends on the public key algorithm used and its
implementation. See \fB\s-1KEY\s0 \s-1GENERATION\s0 \s-1OPTIONS\s0\fR below for more details.
.Ip "\fB\-genparam\fR" 4
generate a set of parameters instead of a private key. If used this option must
precede and \fB\-algorithm\fR, \fB\-paramfile\fR or \fB\-pkeyopt\fR options.
.Ip "\fB\-paramfile filename\fR" 4
Some public key algorithms generate a private key based on a set of parameters.
They can be supplied using this option. If this option is used the public key
algorithm used is determined by the parameters. If used this option must
precede and \fB\-pkeyopt\fR options. The options \fB\-paramfile\fR and \fB\-algorithm\fR
are mutually exclusive.
.Ip "\fB\-text\fR" 4
Print an (unencrypted) text representation of private and public keys and
parameters along with the \s-1PEM\s0 or \s-1DER\s0 structure.
.SH "KEY GENERATION OPTIONS"
The options supported by each algorith and indeed each implementation of an
algorithm can vary. The options for the OpenSSL implementations are detailed
below.
.SH "RSA KEY GENERATION OPTIONS"
.Ip "\fBrsa_keygen_bits:numbits\fR" 4
The number of bits in the generated key. If not specified 1024 is used.
.Ip "\fBrsa_keygen_pubexp:value\fR" 4
The \s-1RSA\s0 public exponent value. This can be a large decimal or
hexadecimal value if preceded by \fB0x\fR. Default value is 65537.
.SH "DSA PARAMETER GENERATION OPTIONS"
.Ip "\fBdsa_paramgen_bits:numbits\fR" 4
The number of bits in the generated parameters. If not specified 1024 is used.
.SH "DH PARAMETER GENERATION OPTIONS"
.Ip "\fBdh_paramgen_prime_len:numbits\fR" 4
The number of bits in the prime parameter \fBp\fR.
.Ip "\fBdh_paramgen_generator:value\fR" 4
The value to use for the generator \fBg\fR.
.SH "EC PARAMETER GENERATION OPTIONS"
.Ip "\fBec_paramgen_curve:curve\fR" 4
the \s-1EC\s0 curve to use.
.SH "GOST2001 KEY GENERATION AND PARAMETER OPTIONS"
Gost 2001 support is not enabled by default. To enable this algorithm,
one should load the ccgost engine in the OpenSSL configuration file.
See README.gost file in the engines/ccgost directiry of the source
distribution for more details.
.PP
Use of a parameter file for the GOST R 34.10 algorithm is optional.
Parameters can be specified during key generation directly as well as
during generation of parameter file.
.Ip "\fBparamset:name\fR" 4
Specifies \s-1GOST\s0 R 34.10-2001 parameter set according to \s-1RFC\s0 4357.
Parameter set can be specified using abbreviated name, object short name or
numeric \s-1OID\s0. Following parameter sets are supported:
.Sp
.Vb 7
\&  paramset   OID               Usage
\&  A          1.2.643.2.2.35.1  Signature
\&  B          1.2.643.2.2.35.2  Signature
\&  C          1.2.643.2.2.35.3  Signature
\&  XA         1.2.643.2.2.36.0  Key exchange
\&  XB         1.2.643.2.2.36.1  Key exchange
\&  test       1.2.643.2.2.35.0  Test purposes
.Ve
.SH "NOTES"
The use of the genpkey program is encouraged over the algorithm specific
utilities because additional algorithm options and ENGINE provided algorithms
can be used.
.SH "EXAMPLES"
Generate an RSA private key using default parameters:
.PP
.Vb 1
\& openssl genpkey -algorithm RSA -out key.pem 
.Ve
Encrypt output private key using 128 bit AES and the passphrase \*(L"hello":
.PP
.Vb 1
\& openssl genpkey -algorithm RSA -out key.pem -aes-128-cbc -pass pass:hello
.Ve
Generate a 2048 bit RSA key using 3 as the public exponent:
.PP
.Vb 2
\& openssl genpkey -algorithm RSA -out key.pem -pkeyopt rsa_keygen_bits:2048 \e
\&                                                -pkeyopt rsa_keygen_pubexp:3
.Ve
Generate 1024 bit DSA parameters:
.PP
.Vb 2
\& openssl genpkey -genparam -algorithm DSA -out dsap.pem \e
\&                                                -pkeyopt dsa_paramgen_bits:1024
.Ve
Generate DSA key from parameters:
.PP
.Vb 1
\& openssl genpkey -paramfile dsap.pem -out dsakey.pem 
.Ve
Generate 1024 bit DH parameters:
.PP
.Vb 2
\& openssl genpkey -genparam -algorithm DH -out dhp.pem \e
\&                                        -pkeyopt dh_paramgen_prime_len:1024
.Ve
Generate DH key from parameters:
.PP
.Vb 1
\& openssl genpkey -paramfile dhp.pem -out dhkey.pem 
.Ve

.rn }` ''
.IX Title "GENPKEY 1"
.IX Name "genpkey - generate a private key"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-out filename\fR"

.IX Item "\fB\-outform \s-1DER\s0|\s-1PEM\s0\fR"

.IX Item "\fB\-pass arg\fR"

.IX Item "\fB\-cipher\fR"

.IX Item "\fB\-engine id\fR"

.IX Item "\fB\-algorithm alg\fR"

.IX Item "\fB\-pkeyopt opt:value\fR"

.IX Item "\fB\-genparam\fR"

.IX Item "\fB\-paramfile filename\fR"

.IX Item "\fB\-text\fR"

.IX Header "KEY GENERATION OPTIONS"

.IX Header "RSA KEY GENERATION OPTIONS"

.IX Item "\fBrsa_keygen_bits:numbits\fR"

.IX Item "\fBrsa_keygen_pubexp:value\fR"

.IX Header "DSA PARAMETER GENERATION OPTIONS"

.IX Item "\fBdsa_paramgen_bits:numbits\fR"

.IX Header "DH PARAMETER GENERATION OPTIONS"

.IX Item "\fBdh_paramgen_prime_len:numbits\fR"

.IX Item "\fBdh_paramgen_generator:value\fR"

.IX Header "EC PARAMETER GENERATION OPTIONS"

.IX Item "\fBec_paramgen_curve:curve\fR"

.IX Header "GOST2001 KEY GENERATION AND PARAMETER OPTIONS"

.IX Item "\fBparamset:name\fR"

.IX Header "NOTES"

.IX Header "EXAMPLES"

