language: ruby
rvm:
  - 2.0.0-p247
script: rspec
services: postgresql
before_script: 
 - "psql -c 'create database piecemaker2_test;' -U postgres"
 - "cp config/config.sample.yml config/config.yml"
 - "sed -i 's/username  : XXX/username  : postgres/g' config/config.yml" 
 - "sed -i 's/password  : XXX/password  : /g' config/config.yml" 
 - "cat config/config.yml" 
 - "rake db:migrate[test]"